services:
  web:
    build: .
    platform: linux/arm64
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: arm64v8/mysql:8.0
    platform: linux/arm64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: juegos
      MYSQL_USER: usuario
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet

  phpmyadmin:
    image: arm64v8/phpmyadmin
    platform: linux/arm64
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on:
      - db
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet: